=== celioso/XML/ejemplo3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="equipos_esp">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="equipo" maxOccurs="unbounded">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="nombre">
                                <xs:complexType mixed="true">
                                    <xs:attribute name="sigla" type="xs:string" default=""/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="valoración" type="xs:double"/>
                            <xs:element name="champion" type="xs:boolean"/>
                            <xs:element name="deporte" type="xs:string" maxOccurs="3"/>
                        </xs:sequence>
                        <xs:attribute name="país" type="xs:string" fixed="España"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="observación" type="xs:string"/>
                <xs:element name="división" type="xs:integer"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== celioso/XML/ejemplo3.xml
<?xml version="1.0" encoding="UTF-8"?>
<equipos_esp xsi:noNamespaceSchemaLocation="ejemplo3.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <equipo país="España">
        un gran equipo, aunque en las últimas temporadas van un poco mal.
        <nombre sigla="FCB">Fútbol club barcelona</nombre>
        <valoración>7.8</valoración>
        <champion>true</champion>
        <deporte>Fútbol</deporte>
        <deporte>Baloncesto</deporte>
        <deporte>Fútbol sala</deporte>
    </equipo>
    <equipo país="España">
        un gran equipo.
        <nombre sigla="FCB">Real Madrid CF</nombre>
        <valoración>10.0</valoración>
        <champion>true</champion>
        <deporte>Fútbol</deporte>
        <deporte>Baloncesto</deporte>
    </equipo>
    <observación>Son equipos de deporte de españa</observación>
    <división>1</división>
</equipos_esp>
